In [1]:
!pip install kaggle
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\gayat\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: kaggle in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (1.6.14)
Requirement already satisfied: six>=1.10 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (2.32.2)
Requirement already satisfied: tqdm in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (4.66.4)
Requirement already satisfied: python-slugify in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (2.2.1)
Requirement already satisfied: bleach in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: colorama in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from tqdm->kaggle) (0.4.6)
Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [2]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile("orders.csv.zip")
zip_ref.extractall()
zip_ref.close()

In [3]:
!pip install pandas
import pandas as pd
df = pd.read_csv("orders.csv", na_values = ['Not Available', 'unknown'])
df["Ship Mode"].unique()

Requirement already satisfied: pandas in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\gayat\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [4]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df.columns
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [5]:
#deriving new columns ..discount, sale price, profit
df["discount"] = df['list_price']*df['discount_percent'] *.01
df["sale_price"] = df['list_price'] - df["discount"]
df["profit"] = df["sale_price"]-df["cost_price"]
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [6]:
#converting order date from object data type to datetime
df['order_date']= pd.to_datetime(df['order_date'],format = "%Y-%m-%d")
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [7]:
df.drop(columns = ['cost_price','list_price','discount_percent'],inplace = True)
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [8]:
!pip install sqlalchemy 
!pip install pymysql
import pymysql

Requirement already satisfied: sqlalchemy in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (2.0.30)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.11.0)

WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\gayat\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: pymysql in c:\users\gayat\appdata\local\programs\python\python310\lib\site-packages (1.1.1)

WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\gayat\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [9]:
import sqlalchemy as sal
engine = sal.create_engine('mysql+pymysql://root:root@localhost/retaildb')
conn=engine.connect()

In [10]:
df.to_sql('df_orders', con=conn , index=False, if_exists = 'append')

9994